language: clojure
script: "lein cljsbuild once min"

deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: "playground-coffeeshop"
  skip_cleanup: true
