language: clojure
script: "lein cljsbuild once min && cd resources/public"
notifications:
  slack: mmmanyfold:eqFezFl7jvwPGIYPH6ORsIgO

deploy:
  provider: s3
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  bucket: "dev.playgroundcoffeeshop.com"
  skip_cleanup: true
